### ISSUE TITLE
When backing up on 0.3.3, LNDg displays the following error

### ISSUE THREAD

**Issue by varacohete** [Start9Labs/lndg-wrapper#3]
![image](https://user-images.githubusercontent.com/105818481/169139288-6df89bbf-3695-45f1-bae2-d833d8591090.png)

**Comment by cryptodread** [comment]
I'm not able to reproduce this error. Can you provide more steps to reproduce?
I used LAN Shared Folders to backup.

**Comment by cryptodread** [comment]
fixed by adding /root/data in the manifest.yaml
